version: "3"

services:
    db:
      build: .
      ports:
        - "${PGPORT}:${PGPORT}"
      environment:
        POSTGRES_DB: ${PGDATABASE}
        POSTGRES_USER: ${PGUSER}
        POSTGRES_PASSWORD: ${PGPASSWORD}
    api:
      image: postgrest/postgrest
      ports:
        - "${PGAPIPORT}:${PGAPIPORT}"
      links:
        - db:db
      environment:
        PGRST_DB_URI: postgres://${PGUSER}:${PGPASSWORD}@db:${PGPORT}/${PGDATABASE}
        PGRST_DB_SCHEMA: "public, api"
        PGRST_DB_ANON_ROLE: ""
        PGRST_SERVER_PROXY_URI: "${PGHOST}:${PGAPIPORT}"
        PGRST_JWT_SECRET: "${JWT_SECRET}"
      depends_on:
        - db